#:schema node_modules/wrangler/config-schema.json
name = "worker"
main = "src/index.ts"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "KV"
id = "584052a94e464845865eaab4fd96191b"
