name: "Client"

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    name: "Check"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client/
    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v4

      - name: "Run npm install"
        run: npm install

      - name: "Run npm run type-check"
        run: npm run type-check

      - name: "Run npm run lint"
        run: npm run lint
